# Site settings
title: Alec writes software
email: alec at mailc dot net
description: > # this means to ignore newlines until "baseurl:"
  I'm Alec Hollingsworth.  I am a software developer in the Southeast.  I like writing code, reading docs, and playing music.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://alecroy.me" # the base hostname & protocol for your site
# twitter_username: 
github_username:  alecroy

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["fenced_code_blocks", "tables"]
#  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

sass:
  sass_dir: _sass
